from typing import Literal, Protocol, TypeVar

note = int | Literal["stop"]
velocity = int
effect = tuple[int, ...]

_T_co = TypeVar("_T_co", covariant=True)
_T_contra = TypeVar("_T_contra", contravariant=True)


class SupportsMath(Protocol[_T_contra, _T_co]):
    def __add__(self, x: _T_contra, /) -> _T_co: ...
    def __radd__(self, x: _T_contra, /) -> _T_co: ...
    def __sub__(self, x: _T_contra, /) -> _T_co: ...
    def __rsub__(self, x: _T_contra, /) -> _T_co: ...
    def __mul__(self, x: _T_contra, /) -> _T_co: ...
    def __rmul__(self, x: _T_contra, /) -> _T_co: ...
    def __divmod__(self, other: _T_contra, /) -> _T_co: ...
    def __rdivmod__(self, other: _T_contra, /) -> _T_co: ...
